
package com.click4care.wsdl._6_5.integrationservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "integrationServicesService", targetNamespace = "http://click4care.com/wsdl/6.5/integrationServices", wsdlLocation = "file:/C:/Users/u61906/AppData/Local/Temp/tempdir2690094665871068761.tmp/integrationServices_1.wsdl")
public class IntegrationServicesService
    extends Service
{

    private final static URL INTEGRATIONSERVICESSERVICE_WSDL_LOCATION;
    private final static WebServiceException INTEGRATIONSERVICESSERVICE_EXCEPTION;
    private final static QName INTEGRATIONSERVICESSERVICE_QNAME = new QName("http://click4care.com/wsdl/6.5/integrationServices", "integrationServicesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/u61906/AppData/Local/Temp/tempdir2690094665871068761.tmp/integrationServices_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INTEGRATIONSERVICESSERVICE_WSDL_LOCATION = url;
        INTEGRATIONSERVICESSERVICE_EXCEPTION = e;
    }

    public IntegrationServicesService() {
        super(__getWsdlLocation(), INTEGRATIONSERVICESSERVICE_QNAME);
    }

    public IntegrationServicesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INTEGRATIONSERVICESSERVICE_QNAME, features);
    }

    public IntegrationServicesService(URL wsdlLocation) {
        super(wsdlLocation, INTEGRATIONSERVICESSERVICE_QNAME);
    }

    public IntegrationServicesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INTEGRATIONSERVICESSERVICE_QNAME, features);
    }

    public IntegrationServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntegrationServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IntegrationServicesPortType
     */
    @WebEndpoint(name = "integrationServicesPort")
    public IntegrationServicesPortType getIntegrationServicesPort() {
        return super.getPort(new QName("http://click4care.com/wsdl/6.5/integrationServices", "integrationServicesPort"), IntegrationServicesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IntegrationServicesPortType
     */
    @WebEndpoint(name = "integrationServicesPort")
    public IntegrationServicesPortType getIntegrationServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://click4care.com/wsdl/6.5/integrationServices", "integrationServicesPort"), IntegrationServicesPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns TaskManagementServicesPortType
     */
    @WebEndpoint(name = "taskManagementServicesPort")
    public TaskManagementServicesPortType getTaskManagementServicesPort() {
        return super.getPort(new QName("http://click4care.com/wsdl/6.5/integrationServices", "taskManagementServicesPort"), TaskManagementServicesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaskManagementServicesPortType
     */
    @WebEndpoint(name = "taskManagementServicesPort")
    public TaskManagementServicesPortType getTaskManagementServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://click4care.com/wsdl/6.5/integrationServices", "taskManagementServicesPort"), TaskManagementServicesPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INTEGRATIONSERVICESSERVICE_EXCEPTION!= null) {
            throw INTEGRATIONSERVICESSERVICE_EXCEPTION;
        }
        return INTEGRATIONSERVICESSERVICE_WSDL_LOCATION;
    }

}
