
package com.click4care.wsdl._6_5.integrationservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.click4care.thinkhealth._6_5.dto.SentTaskType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "taskManagementServicesPortType", targetNamespace = "http://click4care.com/wsdl/6.5/integrationServices")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.click4care.wsdl._6_5.integrationservices.ObjectFactory.class,
    com.click4care.thinkhealth._6_5.dto.ObjectFactory.class,
    com.click4care.thinkhealth.core.dto.ObjectFactory.class
})
public interface TaskManagementServicesPortType {


    /**
     * 
     * @param part1
     */
    @WebMethod
    public void abortTask(
        @WebParam(name = "abortTaskValue", targetNamespace = "http://click4care.com/wsdl/6.5/integrationServices", partName = "part1")
        long part1);

    /**
     * 
     * @param part1
     */
    @WebMethod
    public void cancelTask(
        @WebParam(name = "taskCancelation", targetNamespace = "http://click4care.com/wsdl/6.5/integrationServices", partName = "part1")
        TaskCancelation part1);

    /**
     * 
     * @param part1
     */
    @WebMethod
    public void completeTask(
        @WebParam(name = "taskCompletion", targetNamespace = "http://click4care.com/wsdl/6.5/integrationServices", partName = "part1")
        TaskCompletion part1);

    /**
     * 
     * @param part1
     */
    @WebMethod
    public void deliverTask(
        @WebParam(name = "taskDelivery", targetNamespace = "http://click4care.com/wsdl/6.5/integrationServices", partName = "part1")
        TaskDelivery part1);

    /**
     * 
     * @param part1
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(name = "sendTaskID", targetNamespace = "http://click4care.com/wsdl/6.5/integrationServices", partName = "part1")
    public long sendTask(
        @WebParam(name = "sendTaskValue", targetNamespace = "http://click4care.com/wsdl/6.5/integrationServices", partName = "part1")
        SentTaskType part1);

    /**
     * 
     * @param part1
     */
    @WebMethod
    public void startTask(
        @WebParam(name = "startTaskValue", targetNamespace = "http://click4care.com/wsdl/6.5/integrationServices", partName = "part1")
        long part1);

}
